---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1m5j245kry50j76qla90j3crmxjwqdpf2jmzc8mjz4rqxk695ac4sfgl8cs
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1m5j245kry50j76qla90j3crmxjwqdpf2jmzc8mjz4rqxk695ac4sfgl8cs
