# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:40Pc0LL5iIM8MsRg,iv:xbHw7ErzPbAWBocLzdILzjqFSfJysoJ2uKGPb5hU0i8=,tag:NL8OTFjnYNVh/OQ0XFF2mw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:j8fJMTHDSppgexmnY/gdNBGui42uSQ==,iv:4zYrU2IqYFW3FpaaoWlASeBw9FEOcsTetQjRrTTpRA4=,tag:muNdft9xZdsaN/1YjBoD2w==,type:str]
    SECRET_SLACK_WEBHOOK: ENC[AES256_GCM,data:oFqrR2oWLak8NOiKhxij+TreZDC3I8c+lHGRtuI9/IJ9GN3lFhPTVXiu7ODaawfuSn1vt60BzMKKuQUCwVSJ75PJZrduMcTT3FydymHNvcd9,iv:nwTJu+ch9xWIorpBRk2rzfLcpDDidlOANODqcoM5au8=,tag:YdoxPb8nz/hxzidjTyt9UA==,type:str]
    address: ENC[AES256_GCM,data:Ww+cv770E3nowJNxET2iV1S0FWvaD4DKo9tlbfypYizdchOzp7dOkVqauMzngtaSWIDrKus5ny8MlP9DXJoTirIASCGVInz8eFDxT1O3vx48,iv:bPvkZXmqiN2PfwUewyZFcabCpsgv1cSTm0wdjN+czDw=,tag:G7x/euNaX/9ZVWem/+HxMg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:m59ZvQ8TrHNJztjdirkAhKAWWxKL1fO0xqPbMtc=,iv:PIsXHTMGPcUMqWSkMsTV8cC18URNUMFxWERQ9P6vP+Y=,tag:G7GU5uNvUwOJWqMIDSGsjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m5j245kry50j76qla90j3crmxjwqdpf2jmzc8mjz4rqxk695ac4sfgl8cs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSUpsUmhUNG5Lak9rQ0hy
            c3JSZGJiT3JZdERwYlJ1UWgwVHFnV1NFTkZrCndQYnFrRTVxYlZiYnYveVppVFV2
            anlsMXhMWEJFSnBHdUhuSi9qVk8xVk0KLS0tIHFaMXFUNGRlcHBVTGF3d25ZMkRZ
            aHdxZmZXZGlHbGVBaERYVzFyNlBXTk0KPTJ1HjQHhLoZ7jp4i/HjLJhcE+4F51wF
            OMn7tIuSK8j4cJwpuPcLMnAZJkTvnS5j/rXP917Dl6HITljLu+Z4eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-31T06:13:00Z"
    mac: ENC[AES256_GCM,data:1RFPK1Q/LRJOGGES8bcV2LY+jzQYp2wX/g0juyWie18OUm46ODCXhEbwDkoVTNK697C0bS42ncIV8/ZlgiLogZVYHKAmUwg8XjXDtbhj4Xs3O35xYcj2oMB2YknLHiEhcjpe1uOAOE5QlmR9ylUO1nS9ffo7a7HjOXRw3bZoX58=,iv:IxF4/Hm9nYMuq2TIIp7YT92zjAc8kP/ubRNMlOPdW94=,tag:Qyc9wZW3Hj1UqFHZ8BEyyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
