---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.92.220-192.168.92.230
  METALLB_TRAEFIK_ADDR: 192.168.92.220
  METALLB_GETH_ADDR: 192.168.92.221
  METALLB_REDIS_ADDR: 192.168.92.222
