---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 23.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "traefik"
        annotations:
          hajimari.io/appName: "alert-manager"
          hajimari.io/enable: "true"
          hajimari.io/icon: "web"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - "alert-manager.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "alert-manager.${SECRET_DOMAIN}"
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/appName: "grafana"
          hajimari.io/enable: "true"
          hajimari.io/icon: "web"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - "grafana.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "grafana.${SECRET_DOMAIN}"
    prometheus:
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "traefik"
        annotations:
          hajimari.io/appName: "prometheus"
          hajimari.io/enable: "true"
          hajimari.io/icon: "web"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - "prometheus.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "prometheus.${SECRET_DOMAIN}"
