---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ullr-deployment
  namespace: crypto
  labels:
    app: ullr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ullr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ullr
    spec:
      containers:
        - name: ullr
          image: owodunni/ullr:0.1.2
          args:
            - "./ullr"
            - track
            - "Transfer(address,address,uint256)"
            - erc20
            - -n
            - "ws://${METALLB_GETH_ADDR}:8546"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      imagePullSecrets:
        - name: dockerconfig
      restartPolicy: Always
status: {}
