---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ullr-deployment
  namespace: crypto
  labels:
    app: ullr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ullr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ullr
    spec:
      containers:
        - image: owodunni/ullr:0.1.2
          name: ullr
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      imagePullSecrets:
        - name: dockerconfig
      restartPolicy: Always
status: {}
