---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  labels:
    io.kompose.service: neo4j
  name: neo4j
  namespace: crypto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - name: neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
          image: neo4j
          env:
            - name: NEO4J_AUTH
              value: "neo4j/test"
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "2000m"
          volumeMounts:
            - mountPath: /data
              name: neo4j-data
      restartPolicy: Always
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data
status: {}
