# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ueg49DGFCP7AfdpiXacm2KAsEVVuOCOcgksiJHw6TExEg3pupQ==,iv:tjxemSAWyanKaHmTYaTX8oacCWjLES/RweYVsxfbhXc=,tag:MNAjk18hRIS2RKmCQFVedw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m5j245kry50j76qla90j3crmxjwqdpf2jmzc8mjz4rqxk695ac4sfgl8cs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Wnp1Q3dpQnRyb29OdjNY
            Uk9oaUY4WS9iL2ZDRURHYllqUWcxbER1S3hNCnhkMW51aXJpZjg4VGZZcWd3U0cz
            TDZDYkw0SEQvbXRtd1F4Zzk4VlFtdVkKLS0tIEZGWmVIN25LRysvOU9vY0NGWktx
            SUVlb1QxWGRoSitpWnZ6bDNlSHA3SW8KLQcd8TUXHPYBCPaUH+QRQdshp691Okos
            49sntNgx77lnfEo8FNY9IGKAx7GYDPZTW/jBLrPlkhFoGP4T7EScmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-19T19:29:04Z"
    mac: ENC[AES256_GCM,data:2ykRpxPvclaQmwT0bFr0uvjRyAXJrTGU0wLYtEgW+U1ystzMfRX5rYi1rw8G+APO97W885SOBqTDJgadyMbk1x1k5qcn8n5ZeGDxrva6CmIQ12Z9fBudlfMTlyHmBCg7FyVFCPC8GuX4XMIgP9RqCCuhwlUDksRd5miIjmsnN7Y=,iv:wrHnVypzavWmwHZv/IvISHmMQ4LqXtPa3/lyjb2Mkko=,tag:3+UP0m5RX35DahF4p9+3ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
